[package]
name = "nats_tester"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
async-nats = "0.33"
futures = "0.3"