[workspace]
members = ["libs/shared_models", "services/perception_service", "services/preprocessing_service"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Daniyal Asylbekov <nekgo2009@gmail.com>"]
edition = "2024"
