services:
    neo4j:
        image: neo4j:5.18.0
        container_name: cs-neo4j
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - ./data/neo4j/data:/data
            - ./data/neo4j/logs:/logs
        environment:
            - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
        networks:
            - symbiont-net

    qdrant:
        image: qdrant/qdrant:v1.7.4
        container_name: cs-qdrant
        ports:
            - '6333:6333'
            - '6334:6334'
        volumes:
            - ./data/qdrant_storage:/qdrant/storage
        networks:
            - symbiont-net

    nats:
        image: nats:2.10.7
        container_name: cs-nats
        ports:
            - '4222:4222'
            - '8222:8222'
        networks:
            - symbiont-net

    perception_service:
        container_name: cs-perception-service
        build:
            context: .
            dockerfile: ./services/perception_service/Dockerfile
        depends_on:
            - nats
        environment:
            - NATS_URL=nats://cs-nats:4222
            - RUST_LOG=info,perception_service=debug
        networks:
            - symbiont-net

    preprocessing_service:
        container_name: cs-preprocessing-service
        build:
            context: .
            dockerfile: ./services/preprocessing_service/Dockerfile
        depends_on:
            - nats
        environment:
            - NATS_URL=nats://cs-nats:4222
            - RUST_LOG=info,preprocessing_service=debug
        networks:
            - symbiont-net

    knowledge_graph_service:
        container_name: cs-knowledge-graph-service
        build:
            context: .
            dockerfile: ./services/knowledge_graph_service/Dockerfile
        depends_on:
            - nats
            - neo4j
        environment:
            - NATS_URL=nats://cs-nats:4222
            - NEO4J_URI=bolt://cs-neo4j:7687
            - NEO4J_USER=${NEO4J_USER}
            - NEO4J_PASSWORD=${NEO4J_PASSWORD}
            - RUST_LOG=info,knowledge_graph_service=debug,neo4rs=info
        networks:
            - symbiont-net

networks:
    symbiont-net:
        driver: bridge
